//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian.

#include "MyAnalysisMessenger.hh"
#include "MyRunAction.hh"
#include "MyAnalysisManager.hh"

#include "G4UIdirectory.hh"
#include "G4UIcmdWithAnInteger.hh"
#include "G4UIcmdWithAString.hh"
#include "G4ios.hh"
#include "Randomize.hh"

MyAnalysisMessenger::MyAnalysisMessenger(MyRunAction *runAction)
    : G4UImessenger(),
      fRunAction(runAction)
{
    fFileNameCmd1 = new G4UIcmdWithAString("/MyRun/SetNtupleFileName", this);
    fFileNameCmd1->SetGuidance("set the output filename");
    fFileNameCmd1->SetParameterName("fileName", true);
    fFileNameCmd1->SetDefaultValue("output.root");
    fFileNameCmd1->AvailableForStates(G4State_PreInit, G4State_Idle);

    fFileNameCmd2 = new G4UIcmdWithAString("/MyRun/SetAnalysisFileName", this);
    fFileNameCmd2->SetGuidance("set the output filename");
    fFileNameCmd2->SetParameterName("fileName", true);
    fFileNameCmd2->SetDefaultValue("output.root");
    fFileNameCmd2->AvailableForStates(G4State_PreInit, G4State_Idle);
}

MyAnalysisMessenger::~MyAnalysisMessenger()
{
    delete fFileNameCmd1;
    delete fFileNameCmd2;
}

void MyAnalysisMessenger::SetNewValue(G4UIcommand *command, G4String newValues)
{
    if (command == fFileNameCmd1)
    {
        G4cout << "\n---> Set ntuple output file name: " << newValues << G4endl;
        fRunAction->SetOutputFileName(newValues);
    }

    if (command == fFileNameCmd2)
    {
        G4cout << "\n---> Set analysis output file name: " << newValues << G4endl;
        MyAnalysisManager::GetInstance()->SetFileName(newValues);
    }
}

