//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef MyStepAction_h
#define MyStepAction_h 1

#include "G4UserSteppingAction.hh"
#include "globals.hh"

class MyEvtAction;
class G4LogicalVolume;
class TH1F;

class MyStepAction : public G4UserSteppingAction
{
public:
  MyStepAction(MyEvtAction *evtAction);
  virtual ~MyStepAction();

  virtual void UserSteppingAction(const G4Step *);
private:
  MyEvtAction *fMyEvtAction;

  TH1F *fQE;
};

#endif
