//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#include "G4Event.hh"
#include "G4RunManager.hh"
#include "Verbose.hh"

#include "MyRunAction.hh"
#include "MyEvtAction.hh"
#include "MyAnalysisManager.hh"
//#include "g4root.hh"

MyEvtAction::MyEvtAction()
    : G4UserEventAction()
{
    if (verbose)
        G4cout << "====>MyEvtAction::MyEvtAction()" << G4endl;
}

MyEvtAction::~MyEvtAction()
{
}

void MyEvtAction::BeginOfEventAction(const G4Event *evt)
{
    if (verbose)
        G4cout << "====>MyEvtAction::BeginOfEventAction()" << G4endl;
    MyAnalysisManager::GetInstance()->BeginOfEventAction(evt);
}

void MyEvtAction::EndOfEventAction(const G4Event *evt)
{
    if (verbose)
        G4cout << "====>MyEvtAction::EndOfEventAction()" << G4endl;
    MyAnalysisManager::GetInstance()->EndOfEventAction(evt);
}