//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#include "G4RunManager.hh"
#include "G4Electron.hh"
#include "G4Track.hh"
#include "G4VProcess.hh"
#include "G4LogicalVolume.hh"

#include "MyStackAction.hh"
#include "MyDetectorConstruction.hh"
#include "MyAnalysisManager.hh"
#include "Verbose.hh"
//#include "g4root.hh"

MyStackAction::MyStackAction()
    : G4UserStackingAction(), fKillSecondary(0)
{
    if (verbose)
        G4cout << "====>MyStackAction::MyStackAction()" << G4endl;
}

MyStackAction::~MyStackAction()
{
}

G4ClassificationOfNewTrack MyStackAction::ClassifyNewTrack(const G4Track *aTrack)
{
    //if (verbose)
    //    G4cout << "====>MyStackAction::ClassifyNewTrack(const G4Track* aTrack)" << G4endl;

    return MyAnalysisManager::GetInstance()->ClassifyNewTrack(aTrack);
    //return fUrgent;
}
