//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#include "G4TrackingManager.hh"
#include "G4Track.hh"
#include "Verbose.hh"

#include "MyTrackAction.hh"
#include "MyAnalysisManager.hh"

MyTrackAction::MyTrackAction()
    : G4UserTrackingAction()
{
    if (verbose)
        G4cout << "====>MyTrackAction::MyTrackAction()" << G4endl;
}

MyTrackAction::~MyTrackAction()
{
}

void MyTrackAction::PostUserTrackingAction(const G4Track* aTrack)
{ 
    MyAnalysisManager::GetInstance()->TrackingAction(aTrack);
}
