//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef MyAnalysisMessenger_h
#define MyAnalysisMessenger_h 1

#include "G4UImessenger.hh"
#include "globals.hh"

class MyRunAction;
class G4UIdirectory;
class G4UIcmdWithAnInteger;
class G4UIcmdWithAString;

class MyAnalysisMessenger : public G4UImessenger
{
public:
    MyAnalysisMessenger(MyRunAction *runAction);
    ~MyAnalysisMessenger();

    virtual void SetNewValue(G4UIcommand *, G4String);

private:
    MyRunAction *fRunAction;
    G4UIcmdWithAString *fFileNameCmd1;
    G4UIcmdWithAString *fFileNameCmd2;
};

#endif
